"""Artifact export: serialized pipeline, metadata, scoring script, drift checker.

The bundle is designed so the inference environment needs *no custom code*:
``model.joblib`` holds one fitted sklearn estimator (preprocessing included),
and the generated ``predict.py`` reproduces the stateless preparation recipe
(column renames, date decomposition, text NaN-fill, dtype coercion) recorded in
``metadata.json``.
"""
from __future__ import annotations

import json
import platform
import subprocess
import sys
import time
from pathlib import Path

import joblib
import numpy as np
import pandas as pd
import sklearn

from .config import AutoMLConfig
from .drift import DRIFT_CHECK_SRC
from .models import OPTIONAL
from .utils import AutoMLError, DecisionLog

PREDICT_SRC = '''#!/usr/bin/env python3
"""Batch scoring script — generated by the AutoML template, ships with the artifact.

Usage:
    python predict.py --input new_data.csv --output predictions.csv
    python predict.py --input new_data.parquet --output preds.csv --drift-report

Reads raw rows with the original column names; applies the same stateless
preparation the training run used (recorded in metadata.json); scores with the
serialized pipeline (for binary classification the tuned decision threshold is
already inside the model). Requires: pandas, numpy, joblib, scikit-learn and the
champion's library — see requirements.txt in this folder.
"""
import argparse
import json
import sys
from pathlib import Path

import joblib
import numpy as np
import pandas as pd

HERE = Path(__file__).resolve().parent


def apply_recipe(df, recipe):
    df = df.copy()
    if recipe.get("renamed_columns"):
        df = df.rename(columns=recipe["renamed_columns"])
    for col in recipe.get("boolean_as_int", []):
        if col in df.columns and pd.api.types.is_bool_dtype(df[col]):
            df[col] = df[col].astype("int8")
    for col, derived in recipe.get("date_decompositions", {}).items():
        if col not in df.columns:
            continue
        try:
            parsed = pd.to_datetime(df[col], errors="coerce", format="mixed")
        except (TypeError, ValueError):
            parsed = pd.to_datetime(df[col], errors="coerce")
        if getattr(parsed.dt, "tz", None) is not None:
            parsed = parsed.dt.tz_convert("UTC").dt.tz_localize(None)
        parts = {f"{col}__year": parsed.dt.year, f"{col}__month": parsed.dt.month,
                 f"{col}__day": parsed.dt.day, f"{col}__dayofweek": parsed.dt.dayofweek,
                 f"{col}__hour": parsed.dt.hour,
                 f"{col}__is_weekend": (parsed.dt.dayofweek >= 5).astype("float64"),
                 f"{col}__epoch_days": (parsed - pd.Timestamp("1970-01-01")).dt.days}
        for name in derived:
            df[name] = pd.to_numeric(parts[name], errors="coerce").astype("float64") \\
                if name in parts else np.nan
        df = df.drop(columns=[col])
    for col in recipe.get("text_fillna", []):
        if col in df.columns:
            df[col] = df[col].astype(str).where(df[col].notna(), "")
    for col in recipe.get("categorical_as_string", []):
        if col in df.columns:
            na = df[col].isna()
            df[col] = df[col].astype(str)
            df.loc[na, col] = np.nan
    return df


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--input", required=True, help=".csv or .parquet of raw rows")
    ap.add_argument("--output", required=True, help="destination .csv")
    ap.add_argument("--artifact-dir", default=str(HERE))
    ap.add_argument("--drift-report", action="store_true",
                    help="also print a PSI drift report vs the training distribution")
    args = ap.parse_args()

    art = Path(args.artifact_dir)
    bundle = joblib.load(art / "model.joblib")
    pipe, le = bundle["pipeline"], bundle.get("label_encoder")
    meta = json.loads((art / "metadata.json").read_text())

    path = Path(args.input)
    df_raw = pd.read_parquet(path) if path.suffix.lower() in (".parquet", ".pq") \\
        else pd.read_csv(path)
    df = apply_recipe(df_raw, meta.get("preprocessing_recipe", {}))

    missing = [c for c in meta["features"] if c not in df.columns]
    if missing:
        sys.exit(f"ERROR: input is missing required columns: {missing}\\n"
                 f"Expected features: {meta['features']}")
    X = df[meta["features"]]

    out = pd.DataFrame(index=X.index)
    pred = pipe.predict(X)
    if meta["task"] == "classification":
        # the tuned decision threshold (binary) is applied inside the pipeline
        out["prediction"] = le.inverse_transform(pred.astype(int)) if le is not None else pred
        proba = pipe.predict_proba(X)
        for i, cls in enumerate(meta["classes"]):
            out[f"proba_{cls}"] = proba[:, i]
    else:
        out["prediction"] = pred

    out.to_csv(args.output, index=False)
    print(f"Wrote {len(out):,} predictions -> {args.output}")

    if args.drift_report:
        sys.path.insert(0, str(art))
        from drift_check import check_drift
        report = check_drift(df, meta)
        shifted = report[report["status"].isin(["MODERATE DRIFT", "MAJOR DRIFT"])]
        print("\\nDrift report (PSI vs training):")
        print(shifted.to_string(index=False) if len(shifted) else "  all features stable")


if __name__ == "__main__":
    main()
'''

DOCKERFILE_SRC = '''# Minimal batch-scoring image for the exported artifact.
# Build:  docker build -t automl-scorer .
# Score:  docker run -v $(pwd)/data:/data automl-scorer \\
#             python predict.py --input /data/new.csv --output /data/preds.csv
FROM python:3.12-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY model.joblib metadata.json predict.py drift_check.py ./
CMD ["python", "predict.py", "--help"]
'''


# module name -> PyPI distribution, for the model libraries an artifact can need
_DIST_OF_MODULE = {"sklearn": "scikit-learn", "xgboost": "xgboost",
                   "lightgbm": "lightgbm", "catboost": "catboost"}


def libraries_used(estimator, _seen: set | None = None, _depth: int = 0) -> set:
    """Top-level modules of every estimator reachable from a fitted model.

    Walks ``get_params(deep=False)`` recursively — which reaches Pipeline steps,
    ColumnTransformer branches, blender members, ``TransformedTargetRegressor``
    regressors and threshold/calibration wrappers — plus any fitted attribute
    holding an estimator. Cycle-guarded by object identity and depth-capped.

    Used to pin only the libraries the champion actually needs. Pinning every
    library present in the *training* environment instead is what made the
    Diamonds artifact pull xgboost (and, through it, nvidia-nccl) for a
    champion that never touches it.
    """
    seen = set() if _seen is None else _seen
    found: set = set()
    if _depth > 12 or id(estimator) in seen:
        return found
    seen.add(id(estimator))

    if isinstance(estimator, (list, tuple, set)):
        for item in estimator:
            found |= libraries_used(item, seen, _depth + 1)
        return found
    if isinstance(estimator, dict):
        for item in estimator.values():
            found |= libraries_used(item, seen, _depth + 1)
        return found
    if not hasattr(estimator, "get_params"):
        return found

    found.add(type(estimator).__module__.split(".")[0])
    try:
        params = estimator.get_params(deep=False)
    except Exception:                      # non-conforming third-party estimator
        params = {}
    for value in params.values():
        found |= libraries_used(value, seen, _depth + 1)
    # fitted sub-estimators (e.g. calibrated_classifiers_) that are not params
    for name, value in list(vars(estimator).items()):
        if name.endswith("_") and not name.startswith("_"):
            if hasattr(value, "get_params") or isinstance(value, (list, tuple)):
                found |= libraries_used(value, seen, _depth + 1)
    return found


def pinned_requirements(final_model=None) -> tuple[list, list]:
    """(required pins, optional pins) for the exported artifact.

    Required = the core stack plus exactly the model libraries the champion
    uses. Optional = capabilities the scorer offers but does not need, shipped
    commented out so ``pip install -r requirements.txt`` stays minimal.
    """
    reqs = [f"scikit-learn=={sklearn.__version__}", f"pandas=={pd.__version__}",
            f"numpy=={np.__version__}", f"joblib=={joblib.__version__}"]

    modules = libraries_used(final_model) if final_model is not None else set()
    if final_model is None:                # defensive: pin the whole roster
        modules = {m for m, ok in OPTIONAL.items() if ok}
    for module in sorted(modules):
        dist = _DIST_OF_MODULE.get(module)
        if dist and dist != "scikit-learn":
            reqs.append(f"{dist}=={__import__(module).__version__}")

    optional = []
    try:
        # predict.py accepts parquet input, but scoring CSV/JSON does not need
        # a parquet engine — so pyarrow ships as an opt-in line, not a 50 MB
        # dependency every artifact carries
        import pyarrow
        optional.append(f"pyarrow=={pyarrow.__version__}  # parquet input for predict.py")
    except ImportError:
        pass
    return reqs, optional


def export_artifacts(final_model, label_encoder, metadata: dict, config: AutoMLConfig,
                     log: DecisionLog, X_check: pd.DataFrame,
                     raw_check: pd.DataFrame | None = None) -> Path:
    art = Path(config.artifact_dir)
    art.mkdir(parents=True, exist_ok=True)

    # resolved before serialization so the pins land in metadata.json *and* in
    # the copy embedded in the bundle
    required, optional = pinned_requirements(final_model)
    metadata["inference_libraries"] = required

    bundle = {"pipeline": final_model, "label_encoder": label_encoder, "metadata": metadata}
    model_path = art / "model.joblib"
    joblib.dump(bundle, model_path, compress=3)
    (art / "metadata.json").write_text(json.dumps(metadata, indent=2, default=str))
    (art / "drift_check.py").write_text(DRIFT_CHECK_SRC)
    (art / "predict.py").write_text(PREDICT_SRC)
    (art / "Dockerfile").write_text(DOCKERFILE_SRC)
    lines = ["# Inference requirements for this artifact, pinned to the training",
             "# environment. Only the libraries the champion actually uses are",
             "# listed — the exported pipeline was walked to determine them.",
             *required]
    if optional:
        lines += ["", "# Optional — uncomment if you need it:",
                  *(f"# {o}" for o in optional)]
    (art / "requirements.txt").write_text("\n".join(lines) + "\n")
    log.log("artifacts", f"Inference requirements pinned to the champion's own "
                         f"libraries: {', '.join(required)}")

    # --- round-trip check: the reloaded artifact must predict --------------
    reloaded = joblib.load(model_path)
    _ = reloaded["pipeline"].predict(X_check.head())

    # --- smoke-test the generated scoring script end-to-end ----------------
    # Raw rows exercise the full preparation recipe (renames, date
    # decomposition, text fill); prepared rows are the fallback when the raw
    # frame is unavailable. A failure aborts the export — a broken scorer
    # must never ship.
    smoke_rows = raw_check if raw_check is not None else X_check
    sample_in = art / "_smoke_input.csv"
    sample_out = art / "_smoke_output.csv"
    smoke_rows.head(20).to_csv(sample_in, index=False)
    try:
        res = subprocess.run([sys.executable, str(art / "predict.py"),
                              "--input", str(sample_in), "--output", str(sample_out)],
                             capture_output=True, text=True, timeout=300)
        if res.returncode != 0:
            raise AutoMLError("predict.py smoke test failed — the export was aborted "
                              "because the generated scorer cannot score "
                              f"{'raw' if raw_check is not None else 'prepared'} rows: "
                              f"{res.stderr.strip()[-400:]}")
        log.log("artifacts", "predict.py smoke test passed "
                             f"(scored 20 {'raw' if raw_check is not None else 'prepared'} "
                             "rows through the full recipe + pipeline)")
    finally:
        sample_in.unlink(missing_ok=True)
        sample_out.unlink(missing_ok=True)

    size_mb = model_path.stat().st_size / 1e6
    log.log("artifacts", f"Exported: model.joblib ({size_mb:.2f} MB), metadata.json, "
                         "predict.py, drift_check.py, Dockerfile, requirements.txt "
                         f"-> {art}/")
    return art


def build_metadata(*, task, champion_name, target, features, spec, ta, config,
                   final_score_basis, cv_score, holdout_metrics, threshold,
                   calibration_info, drift_reference, tuned_params, dropped, recipe,
                   decision_log, suspected_leakage, feature_dtypes, best_trees=None,
                   deployment_recommendation=None) -> dict:
    return {
        "task": task,
        "champion": champion_name,
        "target": target,
        "features": features,
        "numeric_features": spec.num_cols,
        "categorical_features": spec.cat_cols,
        "text_features": spec.text_cols,
        "feature_dtypes": feature_dtypes,
        "classes": ta.classes,
        "primary_metric": ta.primary_metric,
        "cv_score": cv_score,
        "cv_score_basis": final_score_basis,
        "holdout_metrics": holdout_metrics,
        "holdout_metrics_note": ("holdout metrics come from a model trained on the training "
                                 "partition only; the exported model was refit on 100% of rows "
                                 "afterwards" if config.refit_on_full_data else
                                 "the exported model is the one that produced these holdout metrics"),
        "optimal_threshold": threshold,          # None unless binary classification
        "deployment_recommendation": deployment_recommendation,
        "calibration": calibration_info,
        "early_stopping_trees": best_trees,
        "suspected_leakage": suspected_leakage,
        "drift_reference": drift_reference,
        "tuned_params": tuned_params,
        "dropped_features": dropped,
        "preprocessing_recipe": recipe,
        "target_stats": ta.stats,
        "decision_log": decision_log,
        "config": {k: v for k, v in config.to_dict().items() if k != "data_path"},
        "versions": {"python": platform.python_version(), "sklearn": sklearn.__version__,
                     **{lib: __import__(lib).__version__ for lib, ok in OPTIONAL.items() if ok}},
        "created_utc": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
    }
