"""Artifact export for forecasting runs.

Ships: the fitted champion (joblib), the final forecast CSV, metadata.json
(panel summary, seasonality, leaderboard, decision log, versions), a generated
``forecast.py`` CLI, a copy of the ``autofc`` package (the pickled models need
it — copying it in keeps the folder self-contained), and report.html.
"""
from __future__ import annotations

import json
import platform
import shutil
import subprocess
import sys
import time
from pathlib import Path

import joblib
import pandas as pd

from .utils import ForecastError

FORECAST_SRC = '''#!/usr/bin/env python3
"""Forecast script — generated by the AutoML forecasting template.

Usage:
    python forecast.py --output forecast.csv
    python forecast.py --horizon 14 --output forecast.csv
    python forecast.py --future-exog future_exog.csv --output forecast.csv

future_exog.csv (only if the run used exogenous regressors): long format with
the original date/series column names plus every exogenous column, covering
the forecast window.

The artifact folder carries its own copy of the `autofc` package, so this
script needs only pandas/numpy/joblib + the champion's libraries installed
(see requirements.txt).
"""
import argparse
import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))               # the bundled autofc package

import joblib
import numpy as np
import pandas as pd


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--output", required=True)
    ap.add_argument("--horizon", type=int, default=None,
                    help="steps ahead (default: the trained horizon)")
    ap.add_argument("--future-exog", default=None,
                    help="CSV with future exogenous values (long format)")
    args = ap.parse_args()

    meta = json.loads((HERE / "metadata.json").read_text())
    bundle = joblib.load(HERE / "model.joblib")
    models, blend_members = bundle["models"], bundle["blend_members"]
    horizon = args.horizon or meta["horizon"]

    future_exog = None
    if meta["exog_cols"]:
        if not args.future_exog:
            sys.exit(f"ERROR: this model uses exogenous regressors {meta['exog_cols']} — "
                     "pass --future-exog with their future values")
        fx = pd.read_csv(args.future_exog)
        fx[meta["date_col"]] = pd.to_datetime(fx[meta["date_col"]])
        for col, coding in meta.get("exog_codings", {}).items():
            if col in fx.columns:
                fx[col] = fx[col].astype(str).map(coding).astype(float)
        sid_col = meta["series_col"]
        future_exog = {}
        groups = fx.groupby(sid_col) if sid_col else [("series_0", fx)]
        for sid, g in groups:
            future_exog[str(sid)] = g.set_index(meta["date_col"])[meta["exog_cols"]]

    member_preds = [models[nm].predict(horizon, future_exog) for nm in blend_members]
    preds = {}
    for sid in member_preds[0]:
        ms = [mp[sid] for mp in member_preds]
        yhat = np.mean([m["yhat"].to_numpy() for m in ms], axis=0)
        if len(ms) == 1:
            lo, hi = ms[0]["lo"].to_numpy(), ms[0]["hi"].to_numpy()
        else:
            lo = hi = np.full(len(yhat), np.nan)
        preds[sid] = pd.DataFrame({"yhat": yhat, "lo": lo, "hi": hi},
                                  index=ms[0].index)

    halves = meta.get("residual_interval_half_widths")
    if halves:
        for sid, p in preds.items():
            # per-series widths, with the pooled widths as the fallback
            h = np.asarray(halves.get(sid) or halves["pooled"], dtype=float)
            if horizon > len(h):    # beyond the backtested horizon: hold the last width
                h = np.append(h, np.full(horizon - len(h), h[-1]))
            p["lo"] = p["yhat"].to_numpy() - h[: len(p)]
            p["hi"] = p["yhat"].to_numpy() + h[: len(p)]

    if meta.get("reconciliation_method"):
        print(f"WARNING: the training run applied '{meta['reconciliation_method']}' "
              "hierarchical reconciliation, which this standalone script does not "
              "reproduce — its output is BASE forecasts (children will not sum "
              "exactly to parents). The committed forecast.csv in this folder is "
              "the reconciled one.", file=sys.stderr)

    rows = []
    for sid, p in preds.items():
        f = p.copy()
        f.insert(0, "series", sid)
        rows.append(f.reset_index(names="ds"))
    out = pd.concat(rows, ignore_index=True)
    out.to_csv(args.output, index=False)
    print(f"Wrote {len(out):,} forecast rows ({len(preds)} series x {horizon} steps) "
          f"-> {args.output}")


if __name__ == "__main__":
    main()
'''


def pinned_requirements(models=None, holiday_country=None) -> list:
    """Inference pins: the core stack plus exactly what the bundled models need.

    Every third-party model import in ``autofc`` is lazy — ``import autofc``
    pulls neither statsmodels nor any GBM — so the artifact only needs the
    union of its own models' ``requires``. Pinning the whole roster instead
    (what this used to do) shipped statsmodels and three GBMs to artifacts
    whose champion was a single Prophet model.

    ``models`` is the bundled {name: forecaster} mapping; ``None`` falls back
    to pinning everything importable, which is the safe answer when the caller
    cannot say what shipped.
    """
    import joblib as _joblib
    import numpy as np
    import scipy
    import sklearn
    reqs = [f"pandas=={pd.__version__}", f"numpy=={np.__version__}",
            f"scipy=={scipy.__version__}", f"joblib=={_joblib.__version__}",
            f"scikit-learn=={sklearn.__version__}"]

    if models is None:
        needed = {"statsmodels", "lightgbm", "xgboost", "catboost", "prophet"}
    else:
        needed = set()
        for model in models.values():
            needed |= set(getattr(model, "requires", ()))
    # holiday features are regenerated for the forecast window at predict time
    if holiday_country:
        needed.add("holidays")

    for lib in sorted(needed):
        try:
            reqs.append(f"{lib}=={__import__(lib).__version__}")
        except ImportError:
            pass
    return reqs


def export_artifacts(fc) -> Path:
    from .backtest import interval_half_widths, residuals_by_step
    from .report import build_forecast_report

    cfg = fc.config
    art = Path(cfg.artifact_dir)
    art.mkdir(parents=True, exist_ok=True)

    # ---- champion bundle ----------------------------------------------------
    blend_members = (fc._blend_members if fc.champion_name.startswith("Blend(")
                     else [fc.champion_name])
    bundle = {"models": fc._final_models, "blend_members": blend_members}
    joblib.dump(bundle, art / "model.joblib", compress=3)

    # residual half-widths for models without native intervals: per-series
    # (so widths respect each series' scale), pooled as the fallback
    halves = None
    if fc.interval_method[fc.champion_name] == "backtest-residual":
        fold_preds = fc.fold_predictions[fc.champion_name]
        pooled = interval_half_widths(
            residuals_by_step(fold_preds, fc.panel, cfg.horizon),
            cfg.interval_level, cfg.horizon)
        halves = {"pooled": [round(float(x), 6) for x in pooled]}
        for sid in fc.panel.frames:
            own = residuals_by_step(fold_preds, fc.panel, cfg.horizon, series_id=sid)
            if sum(len(s) for s in own) >= cfg.horizon:
                halves[str(sid)] = [round(float(x), 6) for x in
                                    interval_half_widths(own, cfg.interval_level,
                                                         cfg.horizon)]

    import sklearn
    import statsmodels
    metadata = {
        "task": "forecasting",
        "champion": fc.champion_name,
        "horizon": cfg.horizon,
        "freq": fc.panel.freq,
        "interval_level": cfg.interval_level,
        "interval_method": fc.interval_method[fc.champion_name],
        # coverage ceiling n/(n+1) imposed by the number of backtest residuals
        # behind a residual band; absent for native-interval champions
        "interval_attainable_level": fc._interval_attainable.get(fc.champion_name),
        "residual_interval_half_widths": halves,
        "seasonality": fc.season_info,
        "date_col": cfg.date_col,
        "series_col": cfg.series_col,
        "target": cfg.target,
        "exog_cols": fc.panel.exog_cols,
        "exog_codings": fc.panel.exog_codings,
        "n_series": len(fc.panel.frames),
        "series": {sid: {"rows": len(f), "start": str(f.index[0]), "end": str(f.index[-1])}
                   for sid, f in fc.panel.frames.items()},
        "dropped_series": fc.panel.dropped,
        "holiday_country": getattr(fc, "holiday_country", None),
        "hierarchy": cfg.hierarchy,
        "reconciliation_method": getattr(fc, "reconciliation_method", None),
        "reconciliation_backtest": (fc.reconciliation_report.to_dict(orient="records")
                                    if getattr(fc, "reconciliation_report", None)
                                    is not None else None),
        "leaderboard": fc.leaderboard.to_dict(orient="records"),
        "deployment_recommendation": {
            "model": getattr(fc, "deployment_pick", None),
            "policy": cfg.champion_policy,
            "applied": cfg.champion_policy == "parsimonious",
            "rule": ("fewest fitted models within one standard error of the best "
                     "mean MASE")},
        "decision_log": fc.log.records,
        "config": {k: v for k, v in cfg.to_dict().items() if k != "data_path"},
        "versions": {"python": platform.python_version(),
                     "statsmodels": statsmodels.__version__,
                     "sklearn": sklearn.__version__},
        "created_utc": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
    }
    (art / "metadata.json").write_text(json.dumps(metadata, indent=2, default=str))
    fc.forecast_frame.to_csv(art / "forecast.csv", index=False)
    (art / "forecast.py").write_text(FORECAST_SRC)
    reqs = pinned_requirements(fc._final_models, cfg.country_holidays)
    (art / "requirements.txt").write_text(
        "\n".join(["# Inference requirements, pinned to the training environment.",
                   "# Only what the bundled champion needs — autofc imports every",
                   "# model library lazily, so nothing else is required.",
                   *reqs]) + "\n")
    fc.log.log("artifacts", "Inference requirements pinned to the champion's own "
                            f"libraries: {', '.join(reqs)}")

    # bundle the package so the pickled models can be loaded anywhere
    pkg_src = Path(__file__).resolve().parent
    pkg_dst = art / "autofc"
    if pkg_dst.exists():
        shutil.rmtree(pkg_dst)
    shutil.copytree(pkg_src, pkg_dst, ignore=shutil.ignore_patterns("__pycache__"))

    # ---- round-trip + script smoke test --------------------------------------
    reloaded = joblib.load(art / "model.joblib")
    assert reloaded["blend_members"] == blend_members
    if not fc.panel.exog_cols:   # script needs --future-exog otherwise
        res = subprocess.run([sys.executable, str(art / "forecast.py"),
                              "--output", str(art / "_smoke.csv")],
                             capture_output=True, text=True, timeout=600)
        (art / "_smoke.csv").unlink(missing_ok=True)
        if res.returncode != 0:
            raise ForecastError("forecast.py smoke test failed — the export was "
                                "aborted because the generated CLI cannot forecast: "
                                f"{res.stderr.strip()[-400:]}")
        fc.log.log("artifacts", "forecast.py smoke test passed")

    build_forecast_report(art / "report.html", fc, metadata)
    fc.log.log("artifacts", f"Exported: model.joblib, metadata.json, forecast.csv, "
                            f"forecast.py, autofc/ (bundled package), report.html -> {art}/")
    fc.metadata = metadata
    return art
